basePath: /
definitions:
  handler.HealthData:
    properties:
      service:
        type: string
      status:
        type: string
      time:
        type: string
    type: object
  handler.HealthSuccessResponse:
    properties:
      code:
        type: string
      data:
        $ref: '#/definitions/handler.HealthData'
      message:
        type: string
    type: object
info:
  contact: {}
  description: A step-by-step Go seckill backend project
  title: go-seckill API
  version: 0.1.0
paths:
  /healthz:
    get:
      description: 返回当前服务的基础健康状态
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthSuccessResponse'
      summary: 健康检查
      tags:
      - base
swagger: "2.0"
