package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"sort"
	"sync"
	"time"
)

type envelope struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    json.RawMessage `json:"data"`
}

type authResponse struct {
	Token string `json:"token"`
}

type productResponse struct {
	ID uint64 `json:"id"`
}

type activityView struct {
	ID uint64 `json:"id"`
}

type loadTestResult struct {
	HTTPStatus int
	Code       string
	Duration   time.Duration
}

type summary struct {
	Total         int
	Concurrency   int
	Stock         int
	HTTPStatuses  map[int]int
	ResultCodes   map[string]int
	AverageMillis float64
	P50Millis     float64
	P95Millis     float64
}

func main() {
	baseURL := flag.String("base-url", "http://127.0.0.1:18092", "API base URL")
	users := flag.Int("users", 40, "number of users to register and use in load test")
	concurrency := flag.Int("concurrency", 20, "number of concurrent seckill attempts")
	stock := flag.Int("stock", 20, "activity stock to use in test")
	flag.Parse()

	client := &http.Client{Timeout: 10 * time.Second}

	adminToken := mustRegisterAndLogin(client, *baseURL, "loadtest_admin", "Password123")
	productID := mustCreateProduct(client, *baseURL, adminToken)
	activityID := mustCreateActivity(client, *baseURL, adminToken, productID, *stock)
	mustPreheat(client, *baseURL, adminToken, activityID)

	userTokens := make([]string, 0, *users)
	for i := 0; i < *users; i++ {
		username := fmt.Sprintf("load_user_%d_%d", time.Now().UnixNano(), i)
		userTokens = append(userTokens, mustRegisterAndLogin(client, *baseURL, username, "Password123"))
	}

	results := runLoad(client, *baseURL, activityID, userTokens, *concurrency)
	report := buildSummary(results, *concurrency, *stock)

	raw, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		panic(err)
	}

	fmt.Println(string(raw))
}

func mustRegisterAndLogin(client *http.Client, baseURL string, username string, password string) string {
	body := map[string]string{
		"username": username,
		"password": password,
	}
	_, _ = doJSON(client, http.MethodPost, baseURL+"/api/v1/auth/register", nil, body)

	httpStatus, data := doJSON(client, http.MethodPost, baseURL+"/api/v1/auth/login", nil, body)
	if httpStatus != http.StatusOK {
		panic(fmt.Sprintf("login failed for %s", username))
	}

	var auth authResponse
	if err := json.Unmarshal(data, &auth); err != nil {
		panic(err)
	}

	return auth.Token
}

func mustCreateProduct(client *http.Client, baseURL string, token string) uint64 {
	body := map[string]any{
		"name":        fmt.Sprintf("load-product-%d", time.Now().UnixNano()),
		"description": "generated by load test",
		"price":       9999,
		"status":      1,
	}

	httpStatus, data := doJSON(client, http.MethodPost, baseURL+"/api/v1/products", bearer(token), body)
	if httpStatus != http.StatusOK {
		panic("create product failed")
	}

	var product productResponse
	if err := json.Unmarshal(data, &product); err != nil {
		panic(err)
	}

	return product.ID
}

func mustCreateActivity(client *http.Client, baseURL string, token string, productID uint64, stock int) uint64 {
	body := map[string]any{
		"product_id":  productID,
		"name":        fmt.Sprintf("load-activity-%d", time.Now().UnixNano()),
		"start_time":  time.Now().Add(-10 * time.Minute).UTC().Format(time.RFC3339Nano),
		"end_time":    time.Now().Add(1 * time.Hour).UTC().Format(time.RFC3339Nano),
		"total_stock": stock,
		"status":      1,
	}

	httpStatus, _ := doJSON(client, http.MethodPost, baseURL+"/api/v1/activities", bearer(token), body)
	if httpStatus != http.StatusOK {
		panic("create activity failed")
	}

	httpStatus, data := doJSON(client, http.MethodGet, baseURL+"/api/v1/activities", nil, nil)
	if httpStatus != http.StatusOK {
		panic("list activity failed")
	}

	var activities []activityView
	if err := json.Unmarshal(data, &activities); err != nil {
		panic(err)
	}
	if len(activities) == 0 {
		panic("no activity created")
	}

	return activities[0].ID
}

func mustPreheat(client *http.Client, baseURL string, token string, activityID uint64) {
	httpStatus, _ := doJSON(client, http.MethodPost, fmt.Sprintf("%s/api/v1/activities/%d/preheat", baseURL, activityID), bearer(token), nil)
	if httpStatus != http.StatusOK {
		panic("preheat failed")
	}
}

func runLoad(client *http.Client, baseURL string, activityID uint64, tokens []string, concurrency int) []loadTestResult {
	sem := make(chan struct{}, concurrency)
	results := make([]loadTestResult, len(tokens))
	var wg sync.WaitGroup

	for idx, token := range tokens {
		wg.Add(1)
		go func(i int, tk string) {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			start := time.Now()
			httpStatus, _, code := doJSONEnvelope(client, http.MethodPost, fmt.Sprintf("%s/api/v1/seckill/activities/%d/attempt", baseURL, activityID), bearer(tk), nil)
			results[i] = loadTestResult{
				HTTPStatus: httpStatus,
				Code:       code,
				Duration:   time.Since(start),
			}
		}(idx, token)
	}

	wg.Wait()
	return results
}

func buildSummary(results []loadTestResult, concurrency int, stock int) summary {
	httpStatuses := make(map[int]int)
	resultCodes := make(map[string]int)
	durations := make([]float64, 0, len(results))
	var totalMillis float64

	for _, result := range results {
		httpStatuses[result.HTTPStatus]++
		resultCodes[result.Code]++
		ms := float64(result.Duration.Milliseconds())
		durations = append(durations, ms)
		totalMillis += ms
	}

	sort.Float64s(durations)

	return summary{
		Total:         len(results),
		Concurrency:   concurrency,
		Stock:         stock,
		HTTPStatuses:  httpStatuses,
		ResultCodes:   resultCodes,
		AverageMillis: totalMillis / float64(len(results)),
		P50Millis:     percentile(durations, 0.50),
		P95Millis:     percentile(durations, 0.95),
	}
}

func percentile(values []float64, ratio float64) float64 {
	if len(values) == 0 {
		return 0
	}

	index := int(float64(len(values)-1) * ratio)
	return values[index]
}

func doJSON(client *http.Client, method string, url string, headers map[string]string, body any) (int, json.RawMessage) {
	httpStatus, data, _ := doJSONEnvelope(client, method, url, headers, body)
	return httpStatus, data
}

func doJSONEnvelope(client *http.Client, method string, url string, headers map[string]string, body any) (int, json.RawMessage, string) {
	var payload []byte
	var err error
	if body != nil {
		payload, err = json.Marshal(body)
		if err != nil {
			panic(err)
		}
	}

	request, err := http.NewRequest(method, url, bytes.NewReader(payload))
	if err != nil {
		panic(err)
	}
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	for key, value := range headers {
		request.Header.Set(key, value)
	}

	response, err := client.Do(request)
	if err != nil {
		panic(err)
	}
	defer response.Body.Close()

	var respEnvelope envelope
	if err := json.NewDecoder(response.Body).Decode(&respEnvelope); err != nil {
		return response.StatusCode, nil, ""
	}

	return response.StatusCode, respEnvelope.Data, respEnvelope.Code
}

func bearer(token string) map[string]string {
	return map[string]string{
		"Authorization": "Bearer " + token,
	}
}
