app:
  name: go-seckill
  env: dev

server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 30s
  shutdown_timeout: 10s

log:
  level: info
  development: true

jwt:
  secret: go-seckill-dev-secret
  issuer: go-seckill
  access_ttl: 2h

mysql:
  host: host.docker.internal
  port: 3306
  user: go_seckill
  password: go_seckill123
  database: go_seckill
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 30m

redis:
  addr: host.docker.internal:6379
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5
